name: Bi Build baseimage

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@3.8.0

      - name: Login to Aliyun Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ env.ALIYUN_REGISTRY_USER }}
          password: ${{ env.ALIYUN_REGISTRY_PASSWORD }}

      - name: Set tag to today's date
        id: date
        run: |
          TAG=$(date +'%Y.%m.%d')
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push Bi baseimage
        uses: docker/build-push-action@v6.12.0
        with:
          context: .
          file: jds/bi/Dockerfile_baseImage
          push: true
          tags: ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/bi:baseimage-${{ env.TAG }}
          platforms: linux/amd64, linux/arm64