name: build bi base image

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/bibase.yml'
      - 'jds/p8/bi/Dockerfile_base'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to Aliyun Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ env.ALIYUN_REGISTRY_USER }}
          password: ${{ env.ALIYUN_REGISTRY_PASSWORD }}

      - name: Set tag
        run: |
          VERSION=$(cat jds/p8/bi/BASE_VERSION)
          echo "current version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          NEW_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
          echo "new version is $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          if [[ ! "$NEW_VERSION" =~ ^v ]]; then
              echo "ERROR: NEW_VERSION does not start with, exiting!"
              exit 1
          fi
          echo "$NEW_VERSION" > jds/p8/bi/BASE_VERSION
          BASE_IMG_TAG=$(cat jds/p8/bi/Dockerfile_base | grep '^ARG PYTHON_IMAGE_TAG=' | awk -F'=' '{print $2}' | sed 's/.*-//' | sed 's/[0-9.]*//g')
          if [[ -z $BASE_IMG_TAG ]]; then
            echo "ERROR: variable BASE_IMG_TAG not defined, exiting!"
            exit 1
          fi
          echo "BASE_IMG_TAG=$BASE_IMG_TAG" >> $GITHUB_ENV

      - name: Build and push Bi baseimage
        uses: docker/build-push-action@v6.11.0
        with:
          context: "{{defaultContext}}:jds/p8/bi"
          file: Dockerfile_base
          push: true
          tags: ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/bi-base:${{ env.VERSION }}-${{ env.BASE_IMG_TAG }}
          platforms: linux/amd64,linux/arm64

      - name: Commit version update
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: "chore: bi baseimage bump version"