name: Bi baseImage CI

on:
  push:
    branches:
      - dev
    paths:
      - 'jds/bi/Dockerfile_baseImage'
      - '.github/workflows/BIbaseImage.yml'
  workflow_dispatch:

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to Aliyun Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ env.ALIYUN_REGISTRY_USER }}
          password: ${{ env.ALIYUN_REGISTRY_PASSWORD }}

      - name: Set tag
        id: date
        run: |
          BUILD_DATE=$(date +'%Y.%m.%d')
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build and push Bi baseimage
        uses: docker/build-push-action@v6.11.0
        with:
          context: "{{defaultContext}}:jds/bi"
          file: Dockerfile_baseImage
          push: true
          tags: ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/bi-base:${{ env.BUILD_DATE }}-${{ env.SHORT_SHA }}
          platforms: linux/amd64